# Generated by Django 2.0.2 on 2018-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='address',
            field=models.CharField(default='Address', max_length=250),
        ),
    ]
