# Generated by Django 2.0.2 on 2018-03-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactperson_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
